### ISSUE TITLE
No matching distribution found for torch==2.0.1+cu118

### ISSUE THREAD

**Issue by francesco086** [avishah3/3D-Screen-Illusion#1]
Hi,

following your instructions I installed it in a venv (btw numpy is missing in your `requirements.txt` and I first got an error because of that).

When I try to run it I get this error:
```
❯ python screen_effect.py
pygame 2.5.0 (SDL 2.28.0, Python 3.10.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/cesco/Desktop/3d-effect/3D-Screen-Illusion-Using-Webcam/screen_effect.py", line 4, in <module>
    from track_eyes import TrackEyes
  File "/Users/cesco/Desktop/3d-effect/3D-Screen-Illusion-Using-Webcam/track_eyes.py", line 3, in <module>
    import cv2
  File "/Users/cesco/Desktop/3d-effect/3D-Screen-Illusion-Using-Webcam/venv/lib/python3.10/site-packages/cv2/__init__.py", line 190, in <module>
    bootstrap()
  File "/Users/cesco/Desktop/3d-effect/3D-Screen-Illusion-Using-Webcam/venv/lib/python3.10/site-packages/cv2/__init__.py", line 184, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/Users/cesco/Desktop/3d-effect/3D-Screen-Illusion-Using-Webcam/venv/lib/python3.10/site-packages/cv2/__init__.py", line 37, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/Users/cesco/.pyenv/versions/3.10.9/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/cesco/Desktop/3d-effect/3D-Screen-Illusion-Using-Webcam/venv/lib/python3.10/site-packages/cv2/typing/__init__.py", line 169, in <module>
    LayerId = cv2.dnn.DictValue
AttributeError: module 'cv2.dnn' has no attribute 'DictValue'
```

I am using Mac Os 13.4.1, but I believe that this is not the issue. More probably is the python version, which one are you using?

**Comment by avishah3** [comment]
Thanks for bringing this to my attention. I just updated the requirements.txt file to what I am currently using. Also, I am running Python 3.10. Let me know if it works now.

**Comment by francesco086** [comment]
When I try to pip install your requirements I now get this error:
```
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement torch==2.0.1+cu118 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==2.0.1+cu118
```

**Comment by francesco086** [comment]
I am thinking, perhaps in this case it could be because of my apple-silicon mac. I will check out if on an intel linux works.

**Comment by francesco086** [comment]
Nope, same error on my linux VM... I change the title of this issue according to this latest error message

**Comment by avishah3** [comment]
You might be running the wrong Python version: "Requires-Python >=3.7,<3.10." Honestly not sure how I can help from my end, but if you find a solution please let me know so I can update the code if necessary.
